version: '3.8'

services:
  ml-api:
    build: .
    ports:
      - "5001:5001"
    environment:
      - FLASK_ENV=production
      - PORT=5001
      - ALLOWED_ORIGINS=http://localhost:4000,https://jobscout2025.netlify.app
      - FIREBASE_KEY_PATH=firebase_key.json
      - LOG_LEVEL=INFO
    volumes:
      - ./firebase_key.json:/app/firebase_key.json:ro
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
